name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v3

      # 2. 安装 Node 20.x（支持 crypto.hash）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. 安装依赖并构建（Vite → dist/）
      - name: Install & Build
        run: |
          npm ci
          npm run build

      # 4. 上传 dist/ 到 Azure Static Web Apps，并跳过 Azure 侧 Oryx 构建
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_PLANT_092484800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # 仓库根，不再用它做构建
          api_location: ""           # 无后端
          output_location: "dist"    # ← 指向打包结果目录
          skip_app_build: true       # ← 跳过 Oryx，直接把 dist/ 上传

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_PLANT_092484800 }}
          action: "close"
