name: Build & Deploy Static Site to Azure Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. 安装 NPM 依赖
      - name: Install dependencies
        run: npm ci

      # 4. 构建项目（Vite -> dist/）
      - name: Build project
        run: npm run build

      # 5. 部署到 Azure Storage Static Website
      - name: Deploy to Azure Storage Static Website
        uses: azure/storage-blob-upload@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container-name: '$web'
          source-directory: './dist'

      # 6. （可选）清理 Cloudflare 缓存
      - name: Clear Cloudflare Cache
        uses: cloudflare/wrangler-action@2.0.2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: 'route purge-by-url https://www.back04oorer.com/*'
